development:
  bucket: kappa.haiku.dev
  access_key_id: AKIAJ4J46ZCPRQCQZXJQ
  secret_access_key: DI9bEqyW0Reaz+LBep0R8vGDNBgD5nOH0iZ7/ipm

test:
  bucket: myapptest
  access_key_id: your key
  secret_access_key: your key

production:
  bucket: kappa.haiku
  access_key_id: AKIAJ4J46ZCPRQCQZXJQ
  secret_access_key: DI9bEqyW0Reaz+LBep0R8vGDNBgD5nOH0iZ7/ipm
