development:
  bucket: kappa.haiku.dev
  access_key_id: <%= ENV['access_key'] %>
  secret_access_key: <%= ENV['secret_key'] %>

test:
  bucket: myapptest
  access_key_id: your key
  secret_access_key: your key

production:
  bucket: kappa.haiku
  access_key_id: <%= ENV['access_key'] %>
  secret_access_key: <%= ENV['secret_key'] %>
